/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages_Java;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author RICK ASTLEY
 */
public class Department_Update_Options extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    public Department_Update_Options() {
        initComponents();
    }
    
    /**
     * function to close the window
     */
    public void close(){
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        UsrList = new javax.swing.JButton();
        back = new javax.swing.JButton();
        UsrList1 = new javax.swing.JButton();
        UsrList2 = new javax.swing.JButton();
        UsrList3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(94, 46, 46));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 208, 185));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("DEPARTMENT");

        UsrList.setBackground(new java.awt.Color(236, 208, 185));
        UsrList.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        UsrList.setForeground(new java.awt.Color(94, 46, 46));
        UsrList.setText("VIEW ALL DEPARTMENT");
        UsrList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrListActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        UsrList1.setBackground(new java.awt.Color(236, 208, 185));
        UsrList1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        UsrList1.setForeground(new java.awt.Color(94, 46, 46));
        UsrList1.setText("UPDATE DEPARTMENT");
        UsrList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrList1ActionPerformed(evt);
            }
        });

        UsrList2.setBackground(new java.awt.Color(236, 208, 185));
        UsrList2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        UsrList2.setForeground(new java.awt.Color(94, 46, 46));
        UsrList2.setText("ADD DEPARTMENT");
        UsrList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrList2ActionPerformed(evt);
            }
        });

        UsrList3.setBackground(new java.awt.Color(236, 208, 185));
        UsrList3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        UsrList3.setForeground(new java.awt.Color(94, 46, 46));
        UsrList3.setText("REMOVE DEPARTMENT");
        UsrList3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrList3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(back)
                .addGap(575, 575, 575)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(603, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsrList1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsrList3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsrList2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsrList, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(679, 679, 679))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(back))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel19)))
                .addGap(156, 156, 156)
                .addComponent(UsrList, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(UsrList2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(UsrList3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(UsrList1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsrListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrListActionPerformed
        close();
        Department_View n = new Department_View();
        n.setVisible(true);
    }//GEN-LAST:event_UsrListActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        close();
        User lp = new User();
        lp.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void UsrList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrList1ActionPerformed
        // TODO add your handling code here:
       close();
        Update_Department ru = new Update_Department();
        ru.setVisible(true);
    }//GEN-LAST:event_UsrList1ActionPerformed

    private void UsrList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrList2ActionPerformed
        // TODO add your handling code here:
        close();
        Update_Department au = new Update_Department();
        au.setVisible(true);
    }//GEN-LAST:event_UsrList2ActionPerformed

    private void UsrList3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrList3ActionPerformed
        // TODO add your handling code here:
         close();
        Remove_Department au = new Remove_Department();
        au.setVisible(true);
    }//GEN-LAST:event_UsrList3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Department_Update_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Department_Update_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Department_Update_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Department_Update_Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Department_Update_Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UsrList;
    private javax.swing.JButton UsrList1;
    private javax.swing.JButton UsrList2;
    private javax.swing.JButton UsrList3;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
